name: Run Benchmarks
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Use Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24'

      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.4.2

      - name: Install
        run: |
          bun ./setup.js

          wget https://github.com/sharkdp/hyperfine/releases/download/v1.19.0/hyperfine_1.19.0_amd64.deb
          sudo dpkg -i hyperfine_1.19.0_amd64.deb

      - name: Run
        run: |
          hyperfine --warmup 1 \
          'bun run --cwd benchmarks/bun test' \
          'bun run --cwd benchmarks/jasmine test' \
          'bun run --cwd benchmarks/jest test' \
          'bun run --cwd benchmarks/vitest test --isolate=false' \
          'bun run --cwd benchmarks/tape test'